name: "CI"

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
      - "!v[0-9]*"
  pull_request:

permissions:
  contents: "read"

jobs:
  build:
    name: "Build"
    uses: "./.github/workflows/build.yaml"
    with:
      publish-coverage: "${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}"
      docker-image-tags: "pfolta/cdrdao2audio:development"
      push-docker-image: "${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}"
    secrets: "inherit"
